[package]
name = "chalmers"
version = "0.1.0"
authors = ["Tock Project Developers <tock-dev@googlegroups.com>"]

[dependencies]
kernel = { path = "../../../../../kernel" }

[lib]
path = "src/hello_world.rs"
